version: "2"
linters:
  default: none
  enable:
    - cyclop
    - errcheck
    - errname
    - errorlint
    - ginkgolinter
    - gocognit
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - perfsprint
    - protogetter
    - staticcheck
    - unused
    - usetesting
  settings:
    cyclop:
      max-complexity: 10
    gocognit:
      min-complexity: 15
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: strict
    warn-unused: true
    presets:
      - common-false-positives
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict
