name: golang no function

on:
  workflow_dispatch:
  pull_request:
defaults:
  run:
    working-directory: go

jobs:
  gofmt_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: run gofmt test
        run: make basic-checks
  escapes_detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: run escapes detect
        run: make escapes_detect
  vulnerability_detect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: run vulnerability detect
        run: make govulncheck
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: make generate
        name: Generate test mocks
      - name: run lint
        run: make golint || true

